language: bash
sudo: required
dist: trusty

before_install:
  - sudo apt-get update
  - sudo apt-get install -y -q gawk curl wget mailutils

install:
  - sudo mkdir -p /opt/ftpgrab/conf /var/log/ftpgrab
  - sudo cp ftpgrab.sh /etc/init.d/ftpgrab
  - sudo chmod +x /etc/init.d/ftpgrab
  - sudo cp ftpgrab.conf /opt/ftpgrab/

before_script:
  - sudo chmod +x tests/*.sh

script:
  - sudo ./tests/test1_wget_md5_text.sh
  - sudo ./tests/test1_wget_sha1_text.sh

after_script:
  - sudo tree -d /opt/ftpgrab/
  - sudo tree -d /var/log/ftpgrab/

notifications:
  slack:
    secure: Q5z9SE+a6BOfiJQpZbGrIloPayObtmEtKYDRwBYQwi5TJiCCt3G4RtvnBHy36DUL+CoNHxeHLCFU5cr2wW/Adu6TR9XoPgr08EIc9oqLiTrQONgDgwGqdk4NrqFLfg0UWVPgDLtfqE7nuAHGRdIeF9zHJX5Xe8xve3yhSsRY5FSoQv8ab0i1SKWSqFsV9JaQdSLyboeJRJv8p6RHt5ayxXY3gBh74qFbK7TGQcJhqhz0i+1CPIujFL6lp6sl8xI0cqx+mTf04mWjv+wovjjtl5c5aAKRhIC9ApT2AcvM8SZ0xxZ6TNsrwb9Wdc3QHH9fLUsDqKr5X+orHVJKQZ4e8i8SkloBDDLiiNRsArLpgzVRxrZ4NdFK+KRBFl26PkuN7k+2vdcpP0dtlKOdZy/ON0ENzt1vK2RGx4SUEGiD8y0VImElZ8doblTc41WKtPUmMn0zz20st/UUbH2vaoV4YpSWf6DbDBgNkCD2hoM8GiHAgnWHIkv1X+RQDXjep+OAfUPp7dEgNZ8e0J8muVbOAJuwevwHMj0Z+uqqnzvXKGgaFL4iq4K1hr9LHn3WM/wFQ9fNce4s3+Shbgi9mwk6sSsl2KDSLL2+0sUF7lkp8VZDQZ5+kLt/qOwRPS/eJvXOLtoyeJ9adZbSzl0weZ574G1mIBCImQCKJf15y+dih5o=
