language: bash
sudo: required
dist: trusty

before_install:
  - sudo apt-get update
  - sudo apt-get install -y -q gawk curl wget mailutils

install:
  - sudo mkdir -p /opt/ftpgrab/conf /var/log/ftpgrab
  - sudo cp ftpgrab.sh /etc/init.d/ftpgrab
  - sudo chmod +x /etc/init.d/ftpgrab
  - sudo cp ftpgrab.conf /opt/ftpgrab/

before_script:
  - sudo chmod +x tests/*.sh

script:
  - cd tests/
  - sudo ./test1_wget_md5_text.sh
  - sudo ./test1_wget_sha1_text.sh

after_script:
  - sudo tree -d /opt/ftpgrab/
  - sudo tree -d /var/log/ftpgrab/

notifications:
  slack:
    secure: WuzYm7aWEyuYdLGA9PMv7RdYQxOhaJMsWbVv3aneTX+y4Pk2MdgWNoUqu87NZsbjvpmH7UpH8JxJeo4QZ2bEVgrFvuozxY8Z3D6C0ZstvWfZyHQWVVwcy0zuLxJ1lFU3nZHftLl6S5zQQ4drJd/JVaI3f7qBVUMOEUDkYh4C678=
